apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-config
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
data:
  appName: {{ .Values.config.appName | quote }}
  appMode: {{ .Values.config.appMode | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
