apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-secret
  namespace: {{ .Values.targetNamespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc | quote }}
